//---------------------------------------------------------------------------

#ifndef un_Data2H
#define un_Data2H
//---------------------------------------------------------------------------
#include <System.Classes.hpp>
#include <Data.DB.hpp>
#include <FireDAC.Comp.Client.hpp>
#include <FireDAC.Comp.DataSet.hpp>
#include <FireDAC.DApt.hpp>
#include <FireDAC.DApt.Intf.hpp>
#include <FireDAC.DatS.hpp>
#include <FireDAC.Phys.Intf.hpp>
#include <FireDAC.Stan.Async.hpp>
#include <FireDAC.Stan.Error.hpp>
#include <FireDAC.Stan.Intf.hpp>
#include <FireDAC.Stan.Option.hpp>
#include <FireDAC.Stan.Param.hpp>
//---------------------------------------------------------------------------
class TData2 : public TDataModule
{
__published:	// IDE-managed Components
	TDataSource *DataHeaderStone;
	TFDQuery *tbHeaderStone;
	TFDAutoIncField *tbHeaderStoneCODIGO;
	TStringField *tbHeaderStoneSTONECODE;
	TStringField *tbHeaderStoneLAYOUT_VERSION;
	TStringField *tbHeaderStoneCOD_CREDENCIAMENTO;
	TDateField *tbHeaderStoneDATA_GERACAO;
	TDateField *tbHeaderStoneDATA_REFERENCIA;
	TDataSource *DataEventoStone;
	TFDQuery *tbEventoStone;
	TFDAutoIncField *tbEventoStoneCODIGO;
	TStringField *tbEventoStoneCODIGO_EVENTO;
	TStringField *tbEventoStoneDESCRICAO_EVENTO;
	TIntegerField *tbEventoStoneTIPO_EVENTO;
	TDateField *tbEventoStonePREVISAO_COBRANCA;
	TFloatField *tbEventoStoneVALOR_EVENTO;
	TIntegerField *tbEventoStoneCODE_TRANSFERENCIA_INTERNA;
	TDateField *tbEventoStoneDATA_COBRANCA;
	TIntegerField *tbEventoStoneCOD_HEADER;
	TStringField *tbEventoStoneTRATADO;
	TStringField *tbEventoStoneSTONECODE;
	TIntegerField *tbEventoStoneARRANJO_PAGAMENTO;
	TIntegerField *tbEventoStoneBANCO;
	TStringField *tbEventoStoneAGENCIA;
	TStringField *tbEventoStoneNUM_CONTA;
	TStringField *tbEventoStoneID_PAGAMENTO;
	TDataSource *DataCredenciadosStone;
	TFDQuery *tbCredenciadosStone;
	TFDAutoIncField *tbCredenciadosStoneCODIGO;
	TDateField *tbCredenciadosStoneDATA_CREDENCIAMENTO;
	TStringField *tbCredenciadosStoneSTONECODE;
	TStringField *tbCredenciadosStoneCNPJ_ESTABELECIMENTO;
	TStringField *tbCredenciadosStoneLIBERADO;
	TDataSource *DataVendaStone;
	TFDQuery *tbVendaStone;
	TFDAutoIncField *tbVendaStoneCODIGO;
	TStringField *tbVendaStoneNSU;
	TStringField *tbVendaStoneCODIGO_TRANSACAO;
	TDateField *tbVendaStoneDATA_AUTORIZACAO;
	TTimeField *tbVendaStoneHORA_AUTORIZACAO;
	TDateField *tbVendaStoneDATA_CAPTURA;
	TTimeField *tbVendaStoneHORA_CAPTURA;
	TStringField *tbVendaStoneINTERNACIONAL;
	TIntegerField *tbVendaStoneCOD_TIPO_CONTA;
	TIntegerField *tbVendaStoneCOD_TIPO_PAGAMENTO;
	TIntegerField *tbVendaStoneTOTAL_PARCELAS;
	TFloatField *tbVendaStoneVALOR_AUTORIZADO;
	TFloatField *tbVendaStoneVALOR_CAPTURADO;
	TFloatField *tbVendaStoneTOTAL_CANCELADO;
	TStringField *tbVendaStoneCODIGO_AUTORIZACAO;
	TIntegerField *tbVendaStoneCOD_BANDEIRA;
	TStringField *tbVendaStoneNUM_CARTAO;
	TIntegerField *tbVendaStoneCOD_TIPO_TERMINAL;
	TStringField *tbVendaStoneNUM_TERMINAL;
	TIntegerField *tbVendaStoneNUM_PARCELA;
	TFloatField *tbVendaStoneVALOR_BRUTO_PARCELA;
	TFloatField *tbVendaStoneVALOR_LIQUIDO_PARCELA;
	TDateField *tbVendaStonePREVISAO_PAGAMENTO;
	TIntegerField *tbVendaStoneCOD_HEADER;
	TStringField *tbVendaStoneTRATADO;
	TStringField *tbVendaStoneSTONECODE;
	TDataSource *DataPagamentoStone;
	TFDQuery *tbPagamentoStone;
	TFDAutoIncField *tbPagamentoStoneCODIGO;
	TIntegerField *tbPagamentoStoneCOD_HEADER;
	TStringField *tbPagamentoStoneNSU;
	TIntegerField *tbPagamentoStoneNUM_PARCELA;
	TFloatField *tbPagamentoStoneVALOR_BRUTO_PARCELA;
	TFloatField *tbPagamentoStoneVALOR_LIQUIDO_PARCELA;
	TDateField *tbPagamentoStonePAGAMENTO_PARCELA;
	TFloatField *tbPagamentoStoneDESCONTO_ANTECIPACAO;
	TDateField *tbPagamentoStonePAGAMENTO_REAL_ANTECIPADO;
	TIntegerField *tbPagamentoStoneARRANJO_PAGAMENTO;
	TFloatField *tbPagamentoStoneVALOR_PAGO;
	TFloatField *tbPagamentoStoneVALOR_PENDENTE_LOJISTA;
	TIntegerField *tbPagamentoStoneBANCO;
	TStringField *tbPagamentoStoneAGENCIA;
	TStringField *tbPagamentoStoneNUM_CONTA;
	TStringField *tbPagamentoStoneTRATADO;
	TStringField *tbPagamentoStoneSTONECODE;
	TStringField *tbPagamentoStoneCODIGO_TRANSACAO;
	TDateField *tbPagamentoStoneDATA_AUTORIZACAO;
	TTimeField *tbPagamentoStoneHORA_AUTORIZACAO;
	TStringField *tbPagamentoStoneID_PAGAMENTO;
	TDataSource *DataCancelamentoStone;
	TFDQuery *tbCancelamentoStone;
	TFDAutoIncField *tbCancelamentoStoneCODIGO;
	TStringField *tbCancelamentoStoneCODIGO_CANCELAMENTO;
	TIntegerField *tbCancelamentoStoneNUM_PARCELA;
	TDateField *tbCancelamentoStoneDATA_CANCELAMENTO;
	TTimeField *tbCancelamentoStoneHORA_CANCELAMENTO;
	TFloatField *tbCancelamentoStoneVALOR_ESTORNADO_CLIENTE;
	TFloatField *tbCancelamentoStoneVALOR_DESCONTADO_LOJISTA;
	TDateField *tbCancelamentoStoneDATA_COBRANCA;
	TIntegerField *tbCancelamentoStoneCOD_HEADER;
	TStringField *tbCancelamentoStoneNSU;
	TDateField *tbCancelamentoStoneDATA_AUTORIZACAO_VENDA;
	TTimeField *tbCancelamentoStoneHORA_AUTORIZACAO_VENDA;
	TDateField *tbCancelamentoStoneDATA_CAPTURA_VENDA;
	TTimeField *tbCancelamentoStoneHORA_CAPTURA_VENDA;
	TDateField *tbCancelamentoStoneDATA_PREVISAO_COBRANCA;
	TStringField *tbCancelamentoStoneTRATADO;
	TStringField *tbCancelamentoStoneSTONECODE;
	TStringField *tbCancelamentoStoneTIPO;
	TStringField *tbCancelamentoStoneID_PAGAMENTO;
	TDataSource *DataBonuscredVenda;
	TFDQuery *tbBonuscredVenda;
	TDataSource *DataBonuscredPagamento;
	TFDQuery *tbBonuscredPagamento;
	TDataSource *DataBonuscredExtra;
	TFDQuery *tbBonuscredExtra;
	TFDAutoIncField *tbBonuscredVendaCODIGO;
	TStringField *tbBonuscredVendaOPERADORA;
	TDateField *tbBonuscredVendaDATA_MOVIMENTO;
	TStringField *tbBonuscredVendaCPF_CNPJ;
	TStringField *tbBonuscredVendaAUTORIZACAO;
	TStringField *tbBonuscredVendaNSU_HOST;
	TStringField *tbBonuscredVendaNSU_PDV;
	TStringField *tbBonuscredVendaPDV;
	TTimeField *tbBonuscredVendaHORA_VENDA;
	TStringField *tbBonuscredVendaCARTAO;
	TStringField *tbBonuscredVendaTIPO_CARTAO;
	TFloatField *tbBonuscredVendaVALOR_BRUTO;
	TFloatField *tbBonuscredVendaVALOR_LIQUIDO;
	TFloatField *tbBonuscredVendaTAXA_PERCENTUAL;
	TIntegerField *tbBonuscredVendaPARCELAS;
	TDateField *tbBonuscredVendaDATA_VENCIMENTO;
	TStringField *tbBonuscredVendaISPB;
	TIntegerField *tbBonuscredVendaNUMERO_CODIGO;
	TStringField *tbBonuscredVendaBANCO;
	TStringField *tbBonuscredVendaAGENCIA;
	TStringField *tbBonuscredVendaCONTA;
	TStringField *tbBonuscredVendaTRATADO;
	TDateField *tbBonuscredVendaDATA_PROCESSAMENTO;
	TTimeField *tbBonuscredVendaHORA_PROCESSAMENTO;
	TIntegerField *tbBonuscredVendaCOD_CLIENTE;
	TFDAutoIncField *tbBonuscredPagamentoCODIGO;
	TStringField *tbBonuscredPagamentoOPERADORA;
	TDateField *tbBonuscredPagamentoDATA_MOVIMENTO;
	TStringField *tbBonuscredPagamentoCPF_CNPJ;
	TStringField *tbBonuscredPagamentoAUTORIZACAO;
	TStringField *tbBonuscredPagamentoNSU_HOST;
	TStringField *tbBonuscredPagamentoNSU_PDV;
	TStringField *tbBonuscredPagamentoPDV;
	TDateField *tbBonuscredPagamentoDATA_VENDA;
	TTimeField *tbBonuscredPagamentoHORA_VENDA;
	TStringField *tbBonuscredPagamentoCARTAO;
	TStringField *tbBonuscredPagamentoTIPO_CARTAO;
	TFloatField *tbBonuscredPagamentoVALOR_BRUTO;
	TFloatField *tbBonuscredPagamentoVALOR_LIQUIDO;
	TIntegerField *tbBonuscredPagamentoPARCELA;
	TIntegerField *tbBonuscredPagamentoQUANTIDADE_PARCELAS;
	TBooleanField *tbBonuscredPagamentoANTECIPACAO;
	TStringField *tbBonuscredPagamentoISPB;
	TIntegerField *tbBonuscredPagamentoNUMERO_CODIGO;
	TStringField *tbBonuscredPagamentoBANCO;
	TStringField *tbBonuscredPagamentoAGENCIA;
	TStringField *tbBonuscredPagamentoCONTA;
	TStringField *tbBonuscredPagamentoTRATADO;
	TDateField *tbBonuscredPagamentoDATA_PROCESSAMENTO;
	TTimeField *tbBonuscredPagamentoHORA_PROCESSAMENTO;
	TIntegerField *tbBonuscredPagamentoCOD_CLIENTE;
	TFDAutoIncField *tbBonuscredExtraCODIGO;
	TStringField *tbBonuscredExtraOPERADORA;
	TDateField *tbBonuscredExtraDATA_MOVIMENTO;
	TStringField *tbBonuscredExtraCPF_CNPJ;
	TStringField *tbBonuscredExtraDOCUMENTO;
	TStringField *tbBonuscredExtraHISTORICO;
	TFloatField *tbBonuscredExtraVALOR_LIQUIDO;
	TStringField *tbBonuscredExtraISPB;
	TIntegerField *tbBonuscredExtraNUMERO_CODIGO;
	TStringField *tbBonuscredExtraBANCO;
	TStringField *tbBonuscredExtraAGENCIA;
	TStringField *tbBonuscredExtraCONTA;
	TStringField *tbBonuscredExtraTRATADO;
	TDateField *tbBonuscredExtraDATA_PROCESSAMENTO;
	TTimeField *tbBonuscredExtraHORA_PROCESSAMENTO;
	TIntegerField *tbBonuscredExtraCOD_CLIENTE;
	TDataSource *DataBonuscredCadastro;
	TFDQuery *tbBonuscredCadastro;
	TFDAutoIncField *tbBonuscredCadastroCODIGO;
	TSingleField *tbBonuscredCadastroCOD_CLIENTE;
	TSingleField *tbBonuscredCadastroCOD_ADQUIRENTE;
	TStringField *tbBonuscredCadastroCODIGO_ESTABELECIMENTO;
	TStringField *tbBonuscredCadastroCNPJ_ESTABELECIMENTO;
	TSingleField *tbBonuscredCadastroCOD_GRUPO;
	TStringField *tbBonuscredCadastroAFFILIATION_KEY;
	TStringField *tbBonuscredCadastroINTEGRA_API_PAGSEGURO;
	TStringField *tbBonuscredCadastroRETORNO_VENDA_PGTO;
	TIntegerField *tbBonuscredCadastroCONCLUIDO;
	TStringField *tbBonuscredCadastroINTEGRA_API_BONUSCRED;
	TDateField *tbPagamentoStoneDATA_CAPTURA;
	TTimeField *tbPagamentoStoneHORA_CAPTURA;
	TIntegerField *tbCancelamentoStoneCOD_PAGAMENTO;
private:	// User declarations
public:		// User declarations
	__fastcall TData2(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TData2 *Data2;
//---------------------------------------------------------------------------
#endif
